name: EconomyPShop
version: "2.0.2-4"
author: onebone
main: onebone\economypshop\EconomyPShop
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
commands:
 pshop:
  description: Management command for creating/removing PShops
  usage: /pshop <create|remove|list> [item[:damage]] [amount] [price] [side]
  permission: economypshop.shop.create

permissions:
 economypshop.*:
  description: Allows all permissions to the player
  children:
   economypshop.shop.*:
    description: Allows player all permissions related to shop
    children:
     economypshop.shop.create:
      description: Allows player to create PShops
      default: true
     economypshop.shop.buy:
      description: Allows player to buy items from shop
      default: true
     economypshop.shop.destroy.others:
      description: Allows player to destroy others' shop
