name: EconomyJob
main: onebone\economyjob\EconomyJob
version: "2.0.4"
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
depend: [EconomyAPI]
author: onebone

commands:
 job:
  description: Job master command
  usage: /job <join|retire|list|me>
  permission: economyjob.command.job
permissions:
 economyjob.command.*:
  description: Allows player to use all of job command
  default: op
  children:
   economyjob.command.job:
    description: Allows player to use /job command
    default: true
    children:
     economyjob.command.job.join:
      description: Allows player to use command that allows to join job
      default: true
     economyjob.command.job.retire:
      description: Allows player to use command that allows to retire job
      default: true
     economyjob.command.job.list:
      description: Allows player to use command that allows to see job list
      default: true
     economyjob.command.job.me:
      description: Allows player to use command that allows to see its job
