CREATE TABLE IF NOT EXISTS land(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	startX INTEGER NOT NULL,
	startZ INTEGER NOT NULL,
	endX INTEGER NOT NULL,
	endZ INTEGER NOT NULL,
	level TEXT NOT NULL,
	owner TEXT NOT NULL,
	invitee TEXT NOT NULL,
	price INTEGER NOT NULL,
	expires INTEGER
)