name: EconomyProperty
main: onebone\economyproperty\EconomyProperty
version: "2.0.7-4"
author: onebone
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
depend:
- EconomyLand
- EconomyAPI
permissions:
 economyproperty.*:
  description: Includes all permissions related to EconomyProperty
  default: op
  children:
   economyproperty.property.*:
    description: Includes all permission related to property area
    default: op
    children:
     economyproperty.property.modify:
      description: Allows player to modify property area
      default: op
     economyproperty.property.remove:
      description: Allows player to remove property
      default: op
   economyproperty.command.property:
    description: Allows player to use property command
    default: op
    children:
     economyproperty.command.property.pos1:
      default: op
      description: Allows player to use /property pos1 command
     economyproperty.command.property.pos2:
      default: op
      description: Allows player to use /property pos2 command
     economyproperty.command.property.make:
      default: op
      description: Allows player to use /property make command
