name: EconomyAirport
version: "2.0.4-2"
author: onebone
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
main: onebone\economyairport\EconomyAirport
depend: [EconomyAPI]

permissions:
 economyairport.*:
  description: Includes all permissions related to EconomyAirport
  children:
   economyairport.create:
    description: Allows player construction of airport
   economyairport.remove:
    description: Allows player to remove airport
