name: EconomyAPI
main: onebone\economyapi\EconomyAPI
version: "2.0.9"
author: onebone
api:
- 2.0.0
- 2.1.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
- 3.0.0-ALPHA13
- 3.0.0-ALPHA14
- 3.0.0-ALPHA15
- 3.0.0-ALPHA16
- 3.0.0-ALPHA17
- 3.0.0-ALPHA18
- 3.0.0-ALPHA19
- 3.0.0-ALPHA20
- 3.1.0
- 3.2.0
- 3.3.0
- 4.0.0

permissions:
 economyapi.*:
  default: op
  description: Allows to control all of functions in EconomyAPI
  children:
   economyapi.command.*:
    default: op
    description: Allows to use all of commands in EconomyAPI
    children:
     economyapi.command.setmoney:
      default: op
      description: Allows to set player's money
     economyapi.command.mymoney:
      description: Allows player to see his/her money
      default: true
     economyapi.command.givemoney:
      description: Allows player to give money to others
      default: op
     economyapi.command.pay:
      description: Allows player to pay to someone
      default: true
     economyapi.command.seemoney:
      description: Allows player to see others' money
      default: true
     economyapi.command.setlang:
      description: Allows player to set his/her language
      default: true
     economyapi.command.topmoney:
      description: Allows player to see top money list
      default: true
     economyapi.command.mystatus:
      description: Allows player to see his/her financial status
      default: true
     economyapi.command.takemoney:
      description: Allows player to take money from others
      default: op
